# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 11, 12, 6, 41, 409653, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
