# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todomodel_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='todoList',
        ),
    ]
