# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_todomodel_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='todoList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.TodoList'),
        ),
    ]
