# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-21 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotemodel',
            name='quote',
            field=models.TextField(default='yeah'),
            preserve_default=False,
        ),
    ]
