# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-21 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('display', '0002_quotemodel_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotemodel',
            name='numberOfTimesShowned',
        ),
        migrations.RemoveField(
            model_name='quotemodel',
            name='submittingUser',
        ),
        migrations.AddField(
            model_name='quotemodel',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
